name: Deploy Sphinx documentation to Pages

on:
  workflow_dispatch:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Doxygen install
      run: sudo apt-get install -y doxygen
    - name: Deployment
      uses: sphinx-notes/pages@v3